// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SendMessage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"msgForm\" class=\"flex flex-col w-full max-w-2xl m-auto\"><textarea name=\"message\" class=\"resize-none border border-black  rounded-lg\" placeholder=\"Write a message\" rows=\"4\"></textarea> <input type=\"submit\" value=\"Send\" class=\"hover:cursor-pointer duration-300\n\t\t\t\t\t bg-purple-200 rounded-lg hover:rounded-xl \n\t\t\t\t\t border border-black text-2xl font-mono font-bold\n\t\t\t\t\t px-1 py-0.5\n\t\t\t\t\t \"></form><div class=\"border border-black\"><p id=\"linkHolder\"></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = sendMessage().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func sendMessage() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_sendMessage_034e`,
		Function: `function __templ_sendMessage_034e(){const linkHolder = document.getElementById("linkHolder")
    const msgForm = document.getElementById("msgForm")

    msgForm.addEventListener('submit', async function (e) {
        e.preventDefault();

    const formData = new FormData(msgForm)
    const message = formData.get("message")
    const response = await fetch('/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ message: message })
    })
    if (!response.ok) {
        alert("Something went wrong... Try again")
        return
    }
    const result = await response.json()
    alert(result.token)
});
}`,
		Call:       templ.SafeScript(`__templ_sendMessage_034e`),
		CallInline: templ.SafeScriptInline(`__templ_sendMessage_034e`),
	}
}
